### ISSUE TITLE
Getting an error after enabling rabbitmq_cloudwatch_exporter but able to get metrics.

### ISSUE THREAD

**Issue by sudesh-urolime** [noxdafox/rabbitmq-cloudwatch-exporter#14] opened 2019-12-11 14:31 UTC
Hi ,

Do we miss something?. Can we analyse below logs.

<Error>\n    <Type>Sender</Type>\n    <Code>MissingParameter</Code>\n    <Message>The parameter MetricData.member.16.Dimensions.member.3.Value is required.\nThe parameter MetricData.member.17.Dimensions.member.3.Value is required.</Message>

**Comment by noxdafox** [comment] 2019-12-16 21:27
Hello,

this is a duplicate of issue #7. I cannot reproduce on any of my environments so I need somebody to help me following the instructions on the last comment.

**Closed by noxdafox** 2019-12-16 21:27 UTC
Labels: duplicate
