### ISSUE TITLE
Issue when using exchange metrics

### ISSUE THREAD

**Issue by SethPyle376** [noxdafox/rabbitmq-cloudwatch-exporter#15] opened 2019-12-16 21:13 UTC
When I enable exporting exchange metrics I get the following

```
2019-12-16 14:08:37.293 [error] <0.335.0> Supervisor 'Elixir.Singleton.Supervisor' had child 'Elixir.Singleton.Manager' started with 'Elixir.Singleton.Manager':start_link('Elixir.RabbitMQCloudWatchExporter.Exporter', [], rabbitmq_cloudwatch_exporter, 'singleton_0bpF3SXqPZTQc80tAf+lu7E5kqQ') at <0.6228.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ExAws.Error',message => <<"ExAws Request Error!\n\n{:error, {:http_error, 400, %{body: \"<ErrorResponse xmlns=\\\"http://monitoring.amazonaws.com/doc/2010-08-01/\\\">\\n  <Error>\\n    <Type>Sender</Type>\\n    <Code>MissingParameter</Code>\\n    <Message>The parameter MetricData.member.12.Dimensions.member.3.Value is required.\\nThe parameter MetricData.member.13.Dimensions.member.3.Value is required.</Message>\\n  </Error>\\n  <RequestId>ef2bff11-f087-433...">>} in 'Elixir.ExAws':'request!'/2 line 66 in context child_terminated
```

**Comment by noxdafox** [comment] 2019-12-16 21:27
Hello, 

this is a duplicate of issue #7. I cannot reproduce on any of my environments so I need somebody to help me following the instructions on the last comment.

**Closed by noxdafox** 2019-12-16 21:27 UTC
Labels: duplicate
